_target_: trainer.transformer.TransformerTrainer

# Copied settings from 270M model from:
#https://github.com/google-deepmind/searchless_chess/blob/main/src/engines/constants.py

lr: 1e-5
embedding_dim: 1024
num_layers: 16
num_heads: 8
batch_size: 128
n_steps: 20000
n_output_bins: 128
